#!/usr/bin/with-contenv bash
#shellcheck shell=bash

if [[ -n "${BEASTHOST}" || -n "${MLATHOST}" ]]; then

    # Build the readsb command line based on piaware options
    READSB_BIN="/usr/local/bin/readsb"
    READSB_CMD=(--net-only)
    READSB_CMD+=(--quiet)

    if [ -n "${LAT}" ]; then
        READSB_CMD+=(--lat "${LAT}")
    fi

    if [ -n "${LONG}" ]; then
        READSB_CMD+=(--lon "${LONG}")
    fi

    if [ -n "${BEASTHOST}" ]; then
        READSB_CMD+=("--net-connector=${BEASTHOST},${BEASTPORT},beast_in")
    fi

    if [ -n "${MLATHOST}" ]; then
        READSB_CMD+=("--net-connector=${MLATHOST},${MLATPORT},beast_in")
    fi

    READSB_CMD+=(--stats-every=3600)
    READSB_CMD+=(--stats-range)

    READSB_CMD+=("--write-json=${DATAPATH}")
    READSB_CMD+=(--write-json-every=1)

    "${READSB_BIN}" "${READSB_CMD[@]}" 2>&1 | awk -W Interactive '{print "[readsb] " $0}'

else
    sleep 86400

fi