#!/usr/bin/with-contenv /bin/bash
#shellcheck shell=bash

NOCOLOR='\033[0m'
LIGHTRED='\033[1;31m'

# Check to make sure the correct command line arguments have been set
EXITCODE=0
if [ -z "${BEASTHOST}" ]; then
  echo -e "${LIGHTRED}ERROR: BEASTHOST environment variable not set${NOCOLOR}"
  EXITCODE=1
fi

# If LAT/LONG are given in isolation...
if [ -z "${LAT}" ]; then
  if [ -n "${LONG}" ]; then
    echo -e "${LIGHTRED}ERROR: Both LAT & LONG environment variables required${NOCOLOR}"
    EXITCODE=1
  fi
fi
if [ -z "${LONG}" ]; then
  if [ -n "${LAT}" ]; then
    echo -e "${LIGHTRED}ERROR: Both LAT & LONG environment variables required${NOCOLOR}"
    EXITCODE=1
  fi
fi

if [ $EXITCODE -ne 0 ]; then
  exit 1
fi

ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
